### ISSUE TITLE
GSE-Generator using "steam_api64.dll" over "steam_api.dll"

### ISSUE THREAD

**Issue by frost988** [brunolee-GIT/GSE-Generator#10]
Hey, I was using the GSE-Generator with the game Kingdom Rush 5 Alliance TD. And after selecting the steam api dll (not 64) the generator was giving me de 64 version and not not "normal" one...

**Comment by brunolee-GIT** [comment]
GSE does not detect whether it is 32 or 64 based on the file name, if it detected it as 64 it may actually be, you just have to rename the file.
Can you upload the file?

When I have some free time, I will start to deal with the problems detected.

**Comment by brunolee-GIT** [comment]
If the steam api is verified as being XX-bit but the name does not match, a window will open asking how to continue.
The file name will now be the same as the original file
(this function is only supported when the files have the original names "steam_api.dll" and "steam_api64.dll")
Thanks!
