### ISSUE TITLE
Crash due to bad characters

### ISSUE THREAD

**Issue by ValiumBear** [brunolee-GIT/GSE-Generator#11]
Example ID: 1913620
Contains ™ in filename. 
From the start the script complains "cannot find the path specified". Folder is created fine but the files are outside of it. Then it crashes.

**Comment by brunolee-GIT** [comment]
The problem was in "...", Windows does not allow creating folders with a period or space at the end of the name.
To solve it, I added the GameID to the end of folder name to solve this problem
Thanks!
