### ISSUE TITLE
Potential substitute to otavepto/gbe_fork

### ISSUE THREAD

**Issue by 50t0r25** [brunolee-GIT/GSE-Generator#13]
There's this new fork of GSE [Detanup01/gbe_fork](https://github.com/Detanup01/gbe_fork), it only has 2 releases so far, but both of them have commits and changes from otavepto themselves including a few other contributors.

**Comment by frost988** [comment]
@brunolee-GIT up! I just tried a new game (TCG Card Shop Simulator) and didn't work with the actual fork, this one above worked :)

**Comment by brunolee-GIT** [comment]
Now gbe_fork used is from Detanup01 repository.
If for some reason can't find, it will download the backup available in my repository
Thanks!
