### ISSUE TITLE
Where does it download the data?

### ISSUE THREAD

**Issue by Darthagnon** [brunolee-GIT/GSE-Generator#2]
I ran the script `GSE_Generator.bat`, and it looked like it downloaded achievement icons etc. but it's not in the game folder and it's not in the legacy  `AppData\Roaming\Goldberg SteamEmu Saves\` folder and it's not in the script folder...

**Comment by Darthagnon** [comment]
![cmd_240509_60](https://github.com/brunolee-GIT/GSE-Generator/assets/20792748/cac81d94-3628-4db2-9a9e-605b55530dde)
Screenshot of while it's running for e.g. Monster Hunter World (582010)

**Comment by brunolee-GIT** [comment]
Hello, I just released version v1.0.1, I think it will solve these problems.
Please continue to report issues, thank you!
