### ISSUE TITLE
Game not found?

### ISSUE THREAD

**Issue by Darthagnon** [brunolee-GIT/GSE-Generator#3]
After entering the ID of a steam game, I get **Game not found**. I've tried many IDs, am connected to the internet and am using v1.0.2.

**Comment by brunolee-GIT** [comment]
try the name of the game

**Comment by Darthagnon** [comment]
Already did, with the same result

**Comment by brunolee-GIT** [comment]
Please, make me a list of the games you're trying, so I can recreate what's going on.
Thanks!

**Comment by Darthagnon** [comment]
- Monster Hunter World - 582010
- Journey - 638230
- Angry Birds Space - 210550
- Insurgency - 222880
- Dying Light - 239140
- Skullgirls - 245170
- Mortal Kombat XL - 307780
- Just Cause 2 - 8190

Basically, every game I have on my PC. The tool does not find achievements or anything for any of their names or Steam IDs

**Comment by brunolee-GIT** [comment]
All games featured in this list were successfully found on my end.
> [!NOTE]
> `The "Tools" folder must be present in the same location as "GSE_Generator.bat".`
> I think that will be your problem.

[Download](https://github.com/brunolee-GIT/GSE-Generator/archive/refs/tags/v1.0.2.zip), extract **everything** and run "GSE_Generator.bat" from the extracted folder

The tool doesn't touch anything you have, neither the game nor your saves, nothing!
Everything will be done in the "GSE_Generator.bat" location with the content presented in the github readme, you decide whether to copy it to the game folder or not.
