### ISSUE TITLE
Generating files bug

### ISSUE THREAD

**Issue by frost988** [brunolee-GIT/GSE-Generator#5]
Bom, sou brasileiro então me darei o direito de escrever em pt-br e como português espero que você me entenda. Primeiramente agradeço ao esforço por fazer esse script maravilhoso, só vim aqui dar um aviso desse bugzinho, primeira vez que vejo. Conforme as imagens ele deu erro (acredito por conta do nome do jogo e seus caracteres especiais), acabou gerando em duas pastas separadas (conforme prints) não sei se faltou algum arquivo ou não mas ta aí. Abraço.

![1](https://github.com/user-attachments/assets/6b4574a2-1321-4a02-baec-1a335cffef63)
![2](https://github.com/user-attachments/assets/6ae1d572-e808-4793-913d-24406c21d28e)
![3](https://github.com/user-attachments/assets/8fa79cad-d165-454c-bea9-4f0d3310457c)
![4](https://github.com/user-attachments/assets/47ca626b-640a-40aa-adb2-969b86305fd8)

**Comment by brunolee-GIT** [comment]
Fixed script for titles with exclamation mark (!)

Download only the [GSE_Generator.bat](https://github.com/brunolee-GIT/GSE-Generator/raw/6e0271634c62270de1e13e375030778ed3314448/GSE_Generator.bat) file (right-click, "Save link as") and replace it.
I'm not going to release a new version with just one fix... (I need more bugs to fix 😄)

Thanks @frost988!
***
<details><summary>Em Português (clica para ver)</summary><br>

Script consertado para títulos com ponto de exclamação (!)


Descarregue apenas o ficheiro <a href="https://github.com/brunolee-GIT/GSE-Generator/raw/6e0271634c62270de1e13e375030778ed3314448/GSE_Generator.bat">GSE_Generator.bat</a> (clique com o botão direito, "Salvar link como") e substitua-o.
Não vou lançar uma versão nova apenas com uma correção... (preciso de mais erros para arranjar 😄)


Obrigado @frost988!
</details>

**Comment by frost988** [comment]
Thanks for your effort @brunolee-GIT, I really appreciate :)
