### ISSUE TITLE
otavepto gbe_fork's gone

### ISSUE THREAD

**Issue by frost988** [brunolee-GIT/GSE-Generator#6]
hey there, i don't want to bother you again but today i saw the gbe fork just vanished from github, and i tried to download it trough the function -emulator (i confess it wanst that smart) i have a backup files from the emu so i have to put it here: "GSE-Generator-1.0.3\Tools\GoldbergSteamEmulator_otavepto" but with wich name? with this: "release-2024_7_7-sdk_1.60.7z" is not working :( sorry to bother you again mate 
![a](https://github.com/user-attachments/assets/321a187e-ec09-4ea3-9fe7-53310a2cb129)

**Comment by frost988** [comment]
[for e](https://pixeldrain.com/u/X4kurdFq) that's the release of emu i've got... idk if the release in gse generator was in different format

**Comment by brunolee-GIT** [comment]
[New release](https://github.com/brunolee-GIT/GSE-Generator/releases/tag/v1.0.4)
Obrigado!

**Comment by frost988** [comment]
Você é o melhor <3 eu que agradeço pela agilidade e esforço no projeto!
