### ISSUE TITLE
Wrong achievements of a specific game

### ISSUE THREAD

**Issue by frost988** [brunolee-GIT/GSE-Generator#9]
Hello, I was using the GSE-Generator as always and I got the wrong achievements of a specific game (all other games is working normally), the game in question is: Keeper's Toll (achievements page: https://steamcommunity.com/stats/2002220/achievements)
I'll send a screenshot here of the achievements i got from the tool... Thx for your support Bruno.

![image](https://github.com/user-attachments/assets/2aa08f4c-0bf1-461e-887f-08b41df0073a)
![image](https://github.com/user-attachments/assets/9ead0e87-11c0-44ab-b70b-9f554e17d98e)

**Comment by brunolee-GIT** [comment]
The problem was because it had the same image.
I added the option "Force English / Fix same achievement name" to solve this problem
Thanks!
